version: '1.0'
name: pipeline-20220615
displayName: pipeline-20220615
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - dev
stages:
  - name: stage-333ce4b5
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - npm install && rm -rf ./dist && npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        strategy:
          retry: '0'
permissions:
  - role: admin
    members: []
